### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by asvinb** [timwright12/Util.move#5]
The README.md file must be updated to the following:
`  import UtilityMove from 'utilitymove';
`
instead of:
`  import UtilityMove from 'UtilityMove';
`
I just copied and pasted from the example in the README file and while everything compiled on my local Mac, the compile script on a Linux machine complained that it did not find the UtilityMove package.
I can create a PR for it :)

**Comment by timwright12** [comment]
all set, thanks!
